name: BKA Event Scraper

on:
  schedule:
    - cron: "45 10 * * *"   # Runs every day at 10:45 UTC
  workflow_dispatch:       # Allows manual triggering from GitHub UI

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Full history for proper rebase

      - name: Pull latest changes first
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug files
        run: |
          pwd
          ls -R

      - name: Run Scraper
        run: python Scraper.py

      - name: Commit and Push Updated Files
        run: |
          git add .
          git commit -m "Auto-update events data [skip ci]" || echo "No changes to commit"
          git push 
