name: BKA Event Scraper

on:
  schedule:
    - cron: "45 10 * * *"   # Runs every day at 06:00 UTC
  workflow_dispatch:       # Allows manual triggering from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scraper
        run: python scraper.py

      - name: Commit and Push Updated Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add events.csv events.json
          git commit -m "Auto-update events data [skip ci]" || echo "No changes to commit"
          git push
